const converter = require('number-to-words');

let fullString = "";

for (let i = 1; i < 124; i++) {
  fullString += converter.toWords(i);
}

fullString = fullString.replace(/\-/g, "");
fullString = fullString.replace(/\ /g, "");

console.log("String length: ", fullString.length);
console.log(fullString);

/**
 * onetwothreefourfivesixseveneightnineteneleventwelvethirteenfourteenfifteensixteenseventeeneighteennineteentwentytwentyonetwentytwotwentythreetwentyfourtwentyfivetwentysixtwentyseventwentyeighttwentyninethirtythirtyonethirtytwothirtythreethirtyfourthirtyfivethirtysixthirtyseventhirtyeightthirtyninefortyfortyonefortytwofortythreefortyfourfortyfivefortysixfortysevenfortyeightfortyninefiftyfiftyonefiftytwofiftythreefiftyfourfiftyfivefiftysixfiftysevenfiftyeightfiftyninesixtysixtyonesixtytwosixtythreesixtyfoursixtyfivesixtysixsixtysevensixtyeightsixtynineseventyseventyoneseventytwoseventythreeseventyfourseventyfiveseventysixseventysevenseventyeightseventynineeightyeightyoneeightytwoeightythreeeightyfoureightyfiveeightysixeightyseveneightyeighteightynineninetyninetyoneninetytwoninetythreeninetyfourninetyfiveninetysixninetysevenninetyeightninetynineonehundredonehundredoneonehundredtwoonehundredthreeonehundredfouronehundredfiveonehundredsixonehundredsevenonehundredeightonehundrednineonehundredtenonehundredelevenonehundredtwelveonehundredthirteenonehundredfourteenonehundredfifteenonehundredsixteenonehundredseventeenonehundredeighteenonehundrednineteenonehundredtwentyonehundredtwentyoneonehundredtwentytwoonehundredtwentythree
 */